// Mock data for SpeakUp Leaders Platform

export const mockUsers = [
  {
    id: '1',
    name: 'أحمد المنصور',
    email: 'ahmed@example.com',
    avatar: null,
    level: 'advanced',
    bio: 'خطيب محترف وعضو في نادي توستماسترز منذ 5 سنوات. متخصص في خطابة الأعمال.',
    country: 'السعودية',
    city: 'الرياض',
    followers: 2840,
    following: 312,
    videosCount: 47,
    coursesCompleted: 12,
    certificates: 8,
    rating: 4.9,
    joinedDate: '2023-03-15',
    badges: ['🏆 بطل التحدي', '⭐ أعلى تقييم', '🎓 متعلم نشيط'],
    socialLinks: { linkedin: '#', twitter: '#', youtube: '#' },
  },
  {
    id: '2',
    name: 'سارة العمري',
    email: 'sara@example.com',
    avatar: null,
    level: 'intermediate',
    bio: 'مدربة تطوير ذاتي وخطيبة تحفيزية. أشارك رحلتي في تطوير مهارات الإلقاء.',
    country: 'الإمارات',
    city: 'دبي',
    followers: 1560,
    following: 210,
    videosCount: 28,
    coursesCompleted: 7,
    certificates: 5,
    rating: 4.7,
    joinedDate: '2023-07-22',
    badges: ['🔥 متحمس', '📚 محاضر'],
    socialLinks: { linkedin: '#', twitter: '#', youtube: '#' },
  },
  {
    id: '3',
    name: 'محمد الزهراني',
    email: 'mohammed@example.com',
    avatar: null,
    level: 'beginner',
    bio: 'طالب هندسة أحاول تطوير مهاراتي في الخطابة. في البداية لكن بعزم!',
    country: 'السعودية',
    city: 'جدة',
    followers: 120,
    following: 450,
    videosCount: 5,
    coursesCompleted: 2,
    certificates: 1,
    rating: 3.8,
    joinedDate: '2024-01-10',
    badges: ['🌱 ناشئ'],
    socialLinks: { linkedin: '#', twitter: '#', youtube: '#' },
  },
];

export const mockCourses = [
  {
    id: '1',
    title: 'أسرار الخطابة الاحترافية',
    description: 'تعلم أساسيات الخطابة من البداية حتى الاحتراف. مع تمارين عملية وأمثلة حقيقية.',
    instructor: 'د. خالد الشمري',
    instructorAvatar: null,
    level: 'beginner',
    duration: '12 ساعة',
    lessonsCount: 24,
    studentsCount: 8420,
    rating: 4.8,
    reviewsCount: 1240,
    price: 0,
    thumbnail: null,
    category: 'خطابة',
    tags: ['خطابة', 'مبتدئ', 'أساسيات'],
    progress: 0,
    featured: true,
    lessons: [
      { id: 'l1', title: 'مقدمة: لماذا الخطابة؟', duration: '18 دقيقة', completed: false },
      { id: 'l2', title: 'أنواع الخطابة ومجالاتها', duration: '22 دقيقة', completed: false },
      { id: 'l3', title: 'التغلب على خوف المسرح', duration: '30 دقيقة', completed: false },
      { id: 'l4', title: 'لغة الجسد وقوتها', duration: '25 دقيقة', completed: false },
      { id: 'l5', title: 'بناء الخطاب الجيد', duration: '35 دقيقة', completed: false },
    ],
  },
  {
    id: '2',
    title: 'قيادة الجماهير: فن التأثير',
    description: 'استراتيجيات القادة في خطاباتهم. كيف تحرّك المشاعر وتصنع الأثر.',
    instructor: 'أ. ريم الخالد',
    instructorAvatar: null,
    level: 'intermediate',
    duration: '18 ساعة',
    lessonsCount: 36,
    studentsCount: 5100,
    rating: 4.9,
    reviewsCount: 890,
    price: 0,
    thumbnail: null,
    category: 'قيادة',
    tags: ['قيادة', 'تأثير', 'متوسط'],
    progress: 45,
    featured: true,
    lessons: [
      { id: 'l1', title: 'القائد والخطيب: الفرق والتكامل', duration: '20 دقيقة', completed: true },
      { id: 'l2', title: 'أسرار الكاريزما', duration: '28 دقيقة', completed: true },
      { id: 'l3', title: 'الاقتباسات وأثرها', duration: '22 دقيقة', completed: false },
    ],
  },
  {
    id: '3',
    title: 'الخطابة المتقدمة: مستوى المحترفين',
    description: 'للمتقدمين الذين يريدون الوصول إلى أعلى المستويات في الأداء الخطابي.',
    instructor: 'م. طارق البستاني',
    instructorAvatar: null,
    level: 'advanced',
    duration: '22 ساعة',
    lessonsCount: 44,
    studentsCount: 2300,
    rating: 4.95,
    reviewsCount: 456,
    price: 0,
    thumbnail: null,
    category: 'خطابة',
    tags: ['متقدم', 'احترافي'],
    progress: 20,
    featured: false,
    lessons: [
      { id: 'l1', title: 'الخطابة في الأزمات', duration: '40 دقيقة', completed: true },
      { id: 'l2', title: 'الارتجال الاحترافي', duration: '35 دقيقة', completed: false },
    ],
  },
  {
    id: '4',
    title: 'التحدث أمام الكاميرا',
    description: 'كيف تبدو واثقاً ومحترفاً أمام الكاميرا في عصر الفيديو الرقمي.',
    instructor: 'أ. نورة السالم',
    instructorAvatar: null,
    level: 'intermediate',
    duration: '8 ساعات',
    lessonsCount: 16,
    studentsCount: 6700,
    rating: 4.7,
    reviewsCount: 980,
    price: 0,
    thumbnail: null,
    category: 'إعلام',
    tags: ['كاميرا', 'فيديو', 'ديجيتال'],
    progress: 0,
    featured: false,
    lessons: [],
  },
  {
    id: '5',
    title: 'فن القصص في الخطابة',
    description: 'تعلم كيف تضفي قصصاً مؤثرة تجعل خطابك لا يُنسى.',
    instructor: 'د. سلمى عبدالرحمن',
    instructorAvatar: null,
    level: 'beginner',
    duration: '10 ساعات',
    lessonsCount: 20,
    studentsCount: 9100,
    rating: 4.85,
    reviewsCount: 1500,
    price: 0,
    thumbnail: null,
    category: 'خطابة',
    tags: ['قصص', 'إلقاء', 'تأثير'],
    progress: 0,
    featured: true,
    lessons: [],
  },
  {
    id: '6',
    title: 'النقاش والجدال الفعّال',
    description: 'مهارات النقاش المنطقي والإقناع، وكيف تتعامل مع الاعتراضات.',
    instructor: 'أ. يوسف العتيبي',
    instructorAvatar: null,
    level: 'advanced',
    duration: '14 ساعة',
    lessonsCount: 28,
    studentsCount: 3400,
    rating: 4.75,
    reviewsCount: 620,
    price: 0,
    thumbnail: null,
    category: 'نقاش',
    tags: ['نقاش', 'إقناع', 'متقدم'],
    progress: 0,
    featured: false,
    lessons: [],
  },
];

export const mockVideos = [
  {
    id: 'v1',
    title: 'خطابتي الأولى على مسرح TEDx',
    description: 'هذه كانت تجربتي الأولى على مسرح TEDx. شاركت موضوع "كيف غيّرت الكلمة حياتي"',
    user: { id: '1', name: 'أحمد المنصور', avatar: null, level: 'advanced' },
    likes: 2840,
    comments: 184,
    views: 42000,
    duration: '7:32',
    tags: ['TEDx', 'تجربة شخصية', 'إلهام'],
    postedAt: '2024-12-05',
    liked: false,
    thumbnail: null,
  },
  {
    id: 'v2',
    title: 'تمرين الارتجال: 60 ثانية على أي موضوع',
    description: 'تحديت نفسي بالارتجال لمدة دقيقة على موضوع عشوائي - موضوع اليوم: "الماء"',
    user: { id: '2', name: 'سارة العمري', avatar: null, level: 'intermediate' },
    likes: 1560,
    comments: 98,
    views: 18000,
    duration: '2:15',
    tags: ['ارتجال', 'تمرين', 'تحدي'],
    postedAt: '2024-12-08',
    liked: true,
    thumbnail: null,
  },
  {
    id: 'v3',
    title: 'أول فيديو لي | هل الخطابة مكتسبة أم فطرية؟',
    description: 'أحاول الإجابة على سؤال يشغل بالي دائماً. آرائكم تهمني!',
    user: { id: '3', name: 'محمد الزهراني', avatar: null, level: 'beginner' },
    likes: 320,
    comments: 45,
    views: 3200,
    duration: '4:10',
    tags: ['رأي', 'نقاش', 'مبتدئ'],
    postedAt: '2024-12-10',
    liked: false,
    thumbnail: null,
  },
  {
    id: 'v4',
    title: 'تقنية الـ 3 ثوانٍ لتحكم في الهدوء قبل الخطاب',
    description: 'سرّ يستخدمه المحترفون لتصفية ذهنهم في اللحظات الحاسمة',
    user: { id: '1', name: 'أحمد المنصور', avatar: null, level: 'advanced' },
    likes: 4100,
    comments: 220,
    views: 68000,
    duration: '3:45',
    tags: ['نصيحة', 'تقنية', 'احترافي'],
    postedAt: '2024-12-01',
    liked: false,
    thumbnail: null,
  },
];

export const mockChallenges = [
  {
    id: 'c1',
    title: 'تحدي الخطاب التحفيزي 🔥',
    description: 'سجّل خطاباً تحفيزياً مدته دقيقتين لا تزيد. الموضوع: "لماذا أسعى إلى التميز؟"',
    week: 'الأسبوع 48 - ديسمبر 2024',
    deadline: '2024-12-20',
    participants: 234,
    prize: 'شهادة بطل التحدي + شارة ذهبية',
    status: 'active',
    submissions: [
      { userId: '1', userName: 'أحمد المنصور', votes: 842, rank: 1 },
      { userId: '2', userName: 'سارة العمري', votes: 631, rank: 2 },
      { userId: '4', userName: 'فاطمة القحطاني', votes: 489, rank: 3 },
      { userId: '5', userName: 'عمر الشريف', votes: 342, rank: 4 },
      { userId: '6', userName: 'لمياء حسن', votes: 278, rank: 5 },
    ],
  },
  {
    id: 'c2',
    title: 'تحدي الارتجال السريع ⚡',
    description: 'تحدث لمدة دقيقة واحدة دون تحضير مسبق على الموضوع الذي ستعرفه لحظة التسجيل.',
    week: 'الأسبوع 47',
    deadline: '2024-12-13',
    participants: 189,
    prize: 'شهادة + ميزة على البروفايل',
    status: 'closed',
    submissions: [
      { userId: '3', userName: 'محمد الزهراني', votes: 512, rank: 1 },
      { userId: '2', userName: 'سارة العمري', votes: 401, rank: 2 },
    ],
  },
  {
    id: 'c3',
    title: 'تحدي لغة الجسد 🤝',
    description: 'سجل خطاباً مدته 3 دقائق بالتركيز الكامل على لغة الجسد والتعابير.',
    week: 'الأسبوع 49',
    deadline: '2024-12-27',
    participants: 0,
    prize: 'شهادة + جلسة تدريب مجانية',
    status: 'upcoming',
    submissions: [],
  },
];

export const mockEvents = [
  {
    id: 'e1',
    title: 'ملتقى الخطباء العرب 2025',
    description: 'الحدث الأكبر في منطقة الشرق الأوسط لخطباء وقادة الفكر. يجمع أكثر من 500 مشارك من 15 دولة.',
    type: 'ملتقى',
    date: '2025-03-15',
    time: '09:00 ص',
    endTime: '06:00 م',
    location: 'فندق فيرمونت',
    city: 'الرياض',
    country: 'السعودية',
    capacity: 500,
    registered: 342,
    price: 0,
    online: false,
    thumbnail: null,
    speakers: ['د. خالد الشمري', 'أ. ريم الخالد', 'م. طارق البستاني'],
    tags: ['ملتقى', 'خطابة', 'قيادة'],
    featured: true,
  },
  {
    id: 'e2',
    title: 'ورشة: إتقان الارتجال في 4 ساعات',
    description: 'ورشة عمل مكثفة مع مدرب محترف لتطوير مهارة الارتجال بشكل جذري.',
    type: 'ورشة',
    date: '2024-12-28',
    time: '02:00 م',
    endTime: '06:00 م',
    location: 'أونلاين - زوم',
    city: 'أونلاين',
    country: 'دولي',
    capacity: 50,
    registered: 38,
    price: 0,
    online: true,
    thumbnail: null,
    speakers: ['أ. نورة السالم'],
    tags: ['ورشة', 'ارتجال', 'أونلاين'],
    featured: false,
  },
  {
    id: 'e3',
    title: 'مسابقة الخطابة الدولية',
    description: 'مسابقة مفتوحة لجميع المستويات. الجوائز تصل إلى 10,000 ريال.',
    type: 'مسابقة',
    date: '2025-02-10',
    time: '10:00 ص',
    endTime: '08:00 م',
    location: 'مركز دبي للمؤتمرات',
    city: 'دبي',
    country: 'الإمارات',
    capacity: 200,
    registered: 67,
    price: 0,
    online: false,
    thumbnail: null,
    speakers: ['لجنة تحكيم دولية'],
    tags: ['مسابقة', 'جوائز', 'دولي'],
    featured: true,
  },
  {
    id: 'e4',
    title: 'ندوة: القيادة بالكلمة',
    description: 'كيف يستخدم القادة العظماء خطاباتهم لتحريك الشعوب وصنع التاريخ.',
    type: 'ندوة',
    date: '2025-01-20',
    time: '07:00 م',
    endTime: '09:00 م',
    location: 'أونلاين - يوتيوب لايف',
    city: 'أونلاين',
    country: 'دولي',
    capacity: 1000,
    registered: 456,
    price: 0,
    online: true,
    thumbnail: null,
    speakers: ['د. خالد الشمري', 'أ. يوسف العتيبي'],
    tags: ['ندوة', 'قيادة', 'مجاني'],
    featured: false,
  },
];

export const mockLeaderboard = [
  { rank: 1, user: { id: '1', name: 'أحمد المنصور', level: 'advanced' }, points: 12840, challengesWon: 8, videosCount: 47, badge: '🏆' },
  { rank: 2, user: { id: '2', name: 'سارة العمري', level: 'intermediate' }, points: 9650, challengesWon: 5, videosCount: 28, badge: '🥈' },
  { rank: 3, user: { id: '7', name: 'فاطمة القحطاني', level: 'advanced' }, points: 8420, challengesWon: 4, videosCount: 35, badge: '🥉' },
  { rank: 4, user: { id: '8', name: 'عمر الشريف', level: 'intermediate' }, points: 7100, challengesWon: 3, videosCount: 22, badge: '' },
  { rank: 5, user: { id: '9', name: 'لمياء حسن', level: 'advanced' }, points: 6800, challengesWon: 3, videosCount: 19, badge: '' },
  { rank: 6, user: { id: '10', name: 'خالد العنزي', level: 'intermediate' }, points: 5920, challengesWon: 2, videosCount: 15, badge: '' },
  { rank: 7, user: { id: '3', name: 'محمد الزهراني', level: 'beginner' }, points: 1240, challengesWon: 1, videosCount: 5, badge: '' },
];

export const platformStats = {
  totalUsers: 24600,
  totalCourses: 48,
  totalVideos: 8900,
  totalEvents: 12,
  totalChallenges: 52,
  countriesCount: 18,
};

export const adminStats = {
  newUsersThisWeek: 384,
  activeUsers: 6200,
  videosUploaded: 234,
  coursesCompleted: 1820,
  eventsRegistrations: 456,
  revenue: 0,
};
